      version: "3.8"

      services:
        immich-server:
          container_name: immich_server
          image: ghcr.io/immich-app/immich-server:release

          ports:
            - "2283:2283"

          volumes:
            - ${cfg.dataDir}/library:/usr/src/app/upload

          env_file:
            - .env

          depends_on:
            - redis
            - database

          restart: always

        redis:
          container_name: immich_redis
          image: docker.io/redis:6.2-alpine
          restart: always

        database:
          container_name: immich_postgres
          image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0

          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: immich

          volumes:
            - ${cfg.dataDir}/postgres:/var/lib/postgresql/data

          restart: always
 
